version: '2.1'

networks:
  mysql:
    external:
      name: mysql

  proxy:
    external:
      name: proxy

services:
  memcached:
    image: memcached

  php:
    image: webvariants/php:7.2-fpm-alpine
    hostname: php
    depends_on:
        - memcached
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - "./:/app"
    tmpfs:
      - "$HOME"
    working_dir: "/app"
    networks:
      - mysql
      - default
    user: "${USER_UID:-1000}:${USER_GID:-1000}"
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    environment:
      PHP_IMAGE_VERSION: "2"
      WEB_ROOT: "/app/web"
      WWW_USER: "${WWW_USER:-martin}"
      WWW_GROUP: "${WWW_GROUP:-martin}"
      PHPINI_SESSION__GC_MAXLIFETIME: "3600"
      PHP_ZEND_EXTENSIONS: "xdebug.so"
      PHPINI_XDEBUG__REMOTE_ENABLE: "1"
      PHPINI_XDEBUG__REMOTE_CONNECT_BACK: "1"
      PHPINI_XDEBUG__REMOTE_PORT: "9000"
      PHPINI_XDEBUG__REMOTE_HANDLER: "dbgp"
      PHPINI_XDEBUG__REMOTE_MODE: "req"
      PHPINI_XDEBUG__REMOTE_AUTOSTART: "true"
      PHPINI_AUTO_START: "0"
      PHPINI_XDEBUG__PROFILER_OUTPUT_DIR: "/app/data"
      PHPINI_XDEBUG__PROFILER_ENABLE: 0
      PHPINI_XDEBUG__PROFILER_ENABLE_TRIGGER: 1
      PHPINI_AUTO_PREPEND_FILE: /xhgui/header.php
      XHGUI_PROBABILITY: 100
      XHGUI_FULL_PROFILING: 1

  cron:
    image: webvariants/php:7.2-fpm-alpine
    hostname: cron
    depends_on:
        - memcached
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - "./:/app"
    working_dir: "/app"
    networks:
      - mysql
      - default
    user: "${USER_UID:-1000}:${USER_GID:-1000}"
    cap_drop:
      - ALL
    ulimits:
      core:
        soft: 0
        hard: 0
    environment:
      PHP_IMAGE_VERSION: "2"
      MINICRON_EXEC: 1
      MINICRON_FILE: /app/crontab

  nginx:
    image: webvariants/nginx-acme-and-more
    volumes:
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./:/app"
    tmpfs:
      - /tmp
    networks:
      - proxy
      - default
    depends_on:
      - php
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.frontend.rule=Host:${HOST:-policat.local}
      - traefik.frontend.passHostHeader=true
      - traefik.docker.network=${NETWORK:-proxy}

  mongo-xh:
    image: percona/percona-server-mongodb:3.6
    # (case sensitive) engine: mmapv1, rocksdb, wiredTiger, inMemory
    command: --storageEngine=inMemory
    environment:
      - MONGO_INITDB_DATABASE=xhprof
    volumes:
      - ./docker/xhgui/xhgui.js:/docker-entrypoint-initdb.d/xhgui.js:ro
      - ./data/mongodb:/data/db # 1001
    networks: ["default"]
    mem_limit: 300m
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: 512k

  xhgui:
    image: webvariants/php:7.3
    depends_on:
        - mongo-xh
    tmpfs:
      - /xhgui/cache
      - /xhgui/data
    volumes:
      - ./docker/xhgui/xhgui_index_cap.php:/start/index_cap.php
    networks:
      - proxy
      - default
    mem_limit: 200m
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    environment:
      PHP_IMAGE_VERSION: "2"
      WEB_ROOT: "/xhgui/webroot"
      APP_DATA: "/xhgui/data"
      XHGUI_CACHE: "/xhgui/cache"
      PHP_TYPO3_INI: "1"
      PHP_OPCACHE_INI: "1"
      PHP_OPCACHE_INI_FAST_SHUTDOWN: "1"
      PHPINI_OPCACHE__VALIDATE_TIMESTAMPS: 0
      START_SCRIPT_DIR: /start
      XHGUI_INDEX_CAP: 104857600 # 100 MB
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.frontend.rule=Host:xhgui.${HOST:-policat.local}
      - traefik.frontend.passHostHeader=true
      - traefik.docker.network=${NETWORK:-proxy}
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: 512k

  mail:
    image: djfarrelly/maildev
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.frontend.rule=Host:mail.${HOST:-policat.local}
      - traefik.docker.network=${NETWORK:-proxy}
    mem_limit: 50M
    memswap_limit: 100M
    networks:
      - proxy
      - default
