<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version253 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('petition_text', 'tyf_title', 'string', '100', array(
             'notnull' => '',
             'default' => '',
             ));
    }

    public function down()
    {
        $this->removeColumn('petition_text', 'tyf_title');
    }
}