<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version254 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('widget', 'show_embed_this', 'integer', '1', array(
             'notnull' => '1',
             'default' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('widget', 'show_embed_this');
    }
}