<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version255 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('widget', 'additional_link_url', 'string', '200', array(
             'notnull' => '',
             ));
        $this->addColumn('widget', 'additional_link_label', 'string', '200', array(
             'notnull' => '',
             ));
    }

    public function down()
    {
        $this->removeColumn('widget', 'additional_link_url');
        $this->removeColumn('widget', 'additional_link_label');
    }
}